version: '3'

services:
 db:
   image: mysql:5.7.19
   volumes:
     - db_data:/var/lib/mysql
   restart: always
   environment:
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wp_user
    MYSQL_PASSWORD: wp_pw

 wordpress:
   depends_on:
     - db
   image: wordpress:latest
   ports:
     - 8000:80
   restart: always
   volumes:
     - ./wordpress/wp-config.php:/usr/src/wordpress/wp-config.php
     - ./wordpress/wp-content/themes/my-theme:/usr/src/wordpress/wp-content/themes/my-theme

volumes:
  db_data:
